/* A packrat parser generated by PackCC 2.2.0 */

#ifndef PCC_INCLUDED_SYSML_PARSER_H
#define PCC_INCLUDED_SYSML_PARSER_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    const char *filename;
    const char *input;
    size_t input_len;
    size_t input_pos;
    int error_count;
    int line;
    int col;
} SysmlParserContext;

#define PCC_GETCHAR(auxil) sysml_getchar(auxil)
#define PCC_ERROR(auxil) sysml_error(auxil)

static inline int sysml_getchar(SysmlParserContext *ctx) {
    if (ctx->input_pos >= ctx->input_len) return EOF;
    int c = (unsigned char)ctx->input[ctx->input_pos++];
    if (c == '\n') {
        ctx->line++;
        ctx->col = 1;
    } else {
        ctx->col++;
    }
    return c;
}

#define ANSI_BOLD    "\x1b[1m"
#define ANSI_RED     "\x1b[31m"
#define ANSI_GREEN   "\x1b[32m"
#define ANSI_RESET   "\x1b[0m"

static inline void sysml_error(SysmlParserContext *ctx) {
    ctx->error_count++;
    const char *line_start = ctx->input;
    int cur_line = 1;
    while (cur_line < ctx->line && *line_start) {
        if (*line_start == '\n') cur_line++;
        line_start++;
    }
    const char *line_end = line_start;
    while (*line_end && *line_end != '\n') line_end++;

    fprintf(stderr, ANSI_BOLD "%s:%d:%d: " ANSI_RED "error: " ANSI_RESET ANSI_BOLD "syntax error" ANSI_RESET "\n",
            ctx->filename, ctx->line, ctx->col);
    fprintf(stderr, " %5d | %.*s\n", ctx->line, (int)(line_end - line_start), line_start);
    fprintf(stderr, "       | " ANSI_GREEN);
    for (int i = 1; i < ctx->col; i++) {
        char c = (i <= (int)(line_end - line_start)) ? line_start[i-1] : ' ';
        fprintf(stderr, "%c", (c == '\t') ? '\t' : ' ');
    }
    fprintf(stderr, "^" ANSI_RESET "\n");
}

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sysml_context_tag sysml_context_t;

sysml_context_t *sysml_create(SysmlParserContext *auxil);
int sysml_parse(sysml_context_t *ctx, void **ret);
void sysml_destroy(sysml_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_SYSML_PARSER_H */
